apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus

  template:
    metadata:
      labels:
        app: event-bus
    
    spec:
      containers:
      - name: event-bus
        image: sadabkhan/event-bus:latest


#comments updating the image used by sadabkhan/event-bus:latest steps are
# 1-> the deployment must used the :latest tag in the (template)pod spec section
# 2-> rebuild the image and push into docker hub using :latest tag
# 3-> run the command kubectl rollout deployment [depl_name]

---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-serv

spec:
  #type: ClusterIp default type no need to mention
  selector:
    app: event-bus
  
  ports:
    - name: event-bus
      protocol: TCP
      port: 5005
      targetPort: 5005