apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "posts.com"
    http:
      paths:
      - path: /post/create
        pathType: Prefix
        backend:
          service:
            name: posts-srv
            port:
              number: 5000

      - path: /post/(.*)/comment
        pathType: Prefix
        backend:
          service:
            name: comments-srv
            port:
              number: 5001

      - path: /posts
        pathType: Prefix
        backend:
          service:
            name: query-srv
            port:
              number: 5002

      - path: /(.*)
        pathType: Exact
        backend:
          service:
            name: client-srv
            port:
              number: 3000