apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation

  template:
    metadata:
      labels:
        app: moderation
    
    spec:
      containers:
      - name: moderation
        image: sadabkhan/moderation:latest
        imagePullPolicy: Always


#comments updating the image used by sadabkhan/moderation:latest steps are
# 1-> the deployment must used the :latest tag in the (template)pod spec section
# 2-> rebuild the image and push into docker hub using :latest tag
# 3-> run the command kubectl rollout restart deployment [depl_name]
# --- used to seprate object both are diffrent obj
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv

spec:
  #type: ClusterIp default type no need to mention
  selector:
    app: moderation
  
  ports:
    - name: moderation
      protocol: TCP
      port: 5003
      targetPort: 5003