apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts

  template:
    metadata:
      labels:
        app: posts
    
    spec:
      containers:
      - name: posts
        image: sadabkhan/posts:latest
        # imagePullPolicy: Always


#comments updating the image used by sadabkhan/posts:latest steps are
# 1-> the deployment must used the :latest tag in the (template)pod spec section
# 2-> rebuild the image and push into docker hub using :latest tag
# 3-> run the command kubectl rollout restart deployment [depl_name]
# --- used to seprate object both are diffrent obj
---
apiVersion: v1
kind: Service
metadata:
  name: posts-srv

spec:
  #type: ClusterIp default type no need to mention
  selector:
    app: posts
  
  ports:
    - name: posts
      protocol: TCP
      port: 5000
      targetPort: 5000